[package]
name = "sclc"
version = "0.1.0"
authors = ["Ziyang Li <liby99@icloud.com>"]
edition = "2018"

[dependencies]
scallop-compiler = { path = "../compiler" }
structopt = "0.3"
proc-macro2 = "1.0"
quote = "1.0"
